#!/usr/local/bin/php
<?php

/** @var \Composer\Autoload\ClassLoader $autoloader */
$autoloader = require __DIR__ . '/../../vendor/autoload.php';

use Worx\CI\Bootstrap;
use Worx\CI\Filter\ProjectTypeFilter;
use Worx\CI\GitPostReceiveHandler;
use Worx\CI\ParserDictionary;

// Extract namespaces to find any available plugins.
$namespaces = Bootstrap::extractNamespaces($autoloader);
$environment = Bootstrap::getEnvironmentVariables();

// Setup the parser plugin dictionary and a project filter.
$parserDictionary = new ParserDictionary($namespaces);
$filter = new ProjectTypeFilter($environment->getProjectType());
$config = Bootstrap::getConfiguration(trim(fgets(STDIN)));
// Get the list of available parser for the give project type.
$plugins = Bootstrap::getValidParsers($environment, $config, $parserDictionary, $filter);

// Operate against the git post-receive hook.
$console = new GitPostReceiveHandler($config, ...$plugins);
$console->run();

?>
