#!/usr/local/bin/php
<?php

$user_directory = trim(shell_exec("cd ~; pwd"));
$hedron_directory = $user_directory . DIRECTORY_SEPARATOR . '.hedron';
$autoloader_file = $hedron_directory . DIRECTORY_SEPARATOR . 'hedron' . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';
if (!file_exists($autoloader_file)) {
  throw new \Exception("Hedron core could not be found, consult a system administrator to determine if this project is setup correctly.");
}
/** @var \Composer\Autoload\ClassLoader $autoloader */
$autoloader = require $autoloader_file;

use Hedron\Bootstrap;
use Hedron\Command\CommandStackFactory;
use Hedron\File\FileSystem;
use Hedron\Filter\ProjectTypeFilter;
use Hedron\GitPostReceiveHandler;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader\PhpFileLoader;

// Extract namespaces to find any available plugins.
$namespaces = Bootstrap::extractNamespaces($autoloader);
$environment = Bootstrap::getEnvironmentVariables();

$container = new ContainerBuilder();
$container->setParameter('namespaces', $namespaces);
$base_directory = __DIR__ . DIRECTORY_SEPARATOR . '..';
$container->setParameter('base.directory', $base_directory);
$service_directories = [
  $base_directory,
];
foreach ($namespaces as $directory) {
  // $directory will correspond to the src dir, so up one level.
  $service_directories[] = $directory . DIRECTORY_SEPARATOR . '..';
}
$loader = new PhpFileLoader($container, new FileLocator($service_directories));
$loader->load('services.php');

// Setup the parser plugin dictionary and a project filter.
/** @var \Hedron\ParserDictionary $parserDictionary */
$parserDictionary = $container->get('dictionary.parser');
$filter = new ProjectTypeFilter($environment->getProjectType());
$config = Bootstrap::getConfiguration(trim(fgets(STDIN)));
// Setup the file system.
$fileSystem = new FileSystem();
// Get the list of available parser for the given project type.
$plugins = Bootstrap::getValidParsers($environment, $config, $fileSystem, $parserDictionary, $filter);

// Operate against the git post-receive hook.
$commandStackFactory = new CommandStackFactory();
$console = new GitPostReceiveHandler($config, $commandStackFactory, ...$plugins);
$console->run();

?>
