#!/usr/local/bin/php
<?php

/** @var \Composer\Autoload\ClassLoader $autoloader */
$autoloader = require __DIR__ . '/../../vendor/autoload.php';

use Worx\CI\Bootstrap;
use Worx\CI\Filter\ProjectTypeFilter;
use Worx\CI\GitPostReceiveHandler;
use Worx\CI\ParserDictionary;

// Extract namespaces to find any available plugins.
$namespaces = Bootstrap::extractNamespaces($autoloader);

// Setup the parser plugin dictionary and a project filter.
$parserDictionary = new ParserDictionary($namespaces);
$filter = new ProjectTypeFilter('php');

// Get the list of available parser for the give project type.
$plugins = Bootstrap::getValidParsers($parserDictionary, $filter);

// Operate against the git post-receive hook.
$console = new GitPostReceiveHandler(trim(fgets(STDIN)), ...$plugins);
$console->run();

?>
